Atualiza empresa campanha
TreinaDev/LojaClubeTD10 pull request #101
Opened 2023-06-28 14:53 UTC by tbkanzaki

Nessa PR, foram feitos os seguintes códigos e ajuste:
* A requisicão get de empresas e toda a lógica envolvida no tratamento dos erros, foram movidas do CompanyController para o ApplicationContoller para um método chamado bring_companies.
* No CompanyController ficou somente a chamada para o metodo bring_companies
* Na action new do PromotionalCampaignsController tem também a chamada para o metodo bring_companies, pois no form do cadastro de Campanhas, as empresas agora são atualizadas com os dados vindos dessa api.
Para essa nova ação, novos testes foram acrescentados quando:
- admin registra nova campanha
* Foram feitos pequenos ajustes nas views index e new da Campanha Promocional, para se adequar a esse novo cenário
* Fizemos correção na validação na data inicial para que seja maior que a data de hoje
* Fizemos correção no texto da mensagem quando a data final é anterior à data inicial
* Foi acrescentada a máscara pra CNPJ no ApplicationHelper para na view index de empresas, o CNPJ ser exibido formatado e os testes foram ajustados

Close #93

2023-06-28 19:16 UTC, ClaufSS reviewed
Tudo ok

2023-06-28 19:56 UTC, luanc202 requested changes

2023-06-28 19:56 UTC, luanc202 commented on app/controllers/application_controller.rb
> +  def response_tratament(response)
Apenas alterar para `response_treatment` aqui para ficar mais coeso, tratamento em inglês é treatment

2023-06-28 19:56 UTC, luanc202 commented on app/controllers/application_controller.rb
> +  def iterates_companies(response)
Aqui colocar `iterate` porque o verbo que vem primeiro deve ser no singular.

2023-06-28 19:56 UTC, luanc202 commented on app/controllers/application_controller.rb
> +  end
Realmente precisa colocar esta função aqui no `application_controller`? Por quê ela não poderia ficar no próprio controller de companies?

2023-06-29 15:35 UTC, tbkanzaki commented on app/controllers/application_controller.rb
> +  end
Porque esse método também é chamado no controller de Campanha.

2023-06-29 18:26 UTC, luanc202 approved these changes

2023-06-29 18:46 UTC, merged