Categoria de produtos
TreinaDev/LojaClubeTD10 pull request #12
Opened 2023-06-07 19:33 UTC by felipel7

Esta pull request implementa a criação e edição de uma categoria de produto.

Close #6

2023-06-07 23:46 UTC, joaorsalmeida submitted a review, later dismissed

2023-06-07 23:46 UTC, joaorsalmeida commented on spec/system/categories/admin_register_product_category_spec.rb
> +    # admin = User.create!(email: "admin@punti.com", password: '123123')
Bora remover linhas comentadas antes de mandar pra revisão ;)

2023-06-07 23:46 UTC, joaorsalmeida commented on spec/system/categories/user_view_product_categories_spec.rb
> +    # Arrange
Não precisa destas linhas, basta deixar uma linha em branco separando cada bloco.

2023-06-07 23:46 UTC, joaorsalmeida commented on app/models/product_category.rb
> +  validates :name, presence: true
Este nome não deveria ser único?

2023-06-09 20:20 UTC, felipel7 commented on spec/system/categories/admin_register_product_category_spec.rb
> +    # admin = User.create!(email: "admin@punti.com", password: '123123')
Linhas removidas. :)

2023-06-09 20:20 UTC, felipel7 commented on spec/system/categories/user_view_product_categories_spec.rb
> +    # Arrange
Linhas removidas. :)

2023-06-09 20:20 UTC, felipel7 commented on app/models/product_category.rb
> +  validates :name, presence: true
Bem lembrando, já adicionamos a validação.

2023-06-12 10:47 UTC, OtavioLins requested changes
Deixei um comentário-sugestão e outro que já é mais importante (o sobre o teste que está faltando). 

Estou comentando isso em todos os PRs de vocês e queria que vocês discutissem sobre. A forma que vocês estão organizando os testes não é, no geral, a mais recomendada. Separar os testes de sistema em pastas menores pode atrapalhar mais do que ajudar. 

O usual é deixar esses testes "soltos" dentro da pasta de sistema, mas com bons nomes, de forma que seja fácil encontrá-los sempre que precisar. Do jeito que está (separado por models e/ou telas, como visto em outros PRs da equipe), conforme mais arquivos forem sendo criados, alguns testes podem começar a ficar perdidos. Um exemplo que inclusive vi em outro PR: se eu tenho um produto que aparece na homepage, onde eu procuro esse teste: na pasta de home ou na pasta de product?

Perceba que, conforme as coisas vão se conectando na aplicação, a organização dos testes de sistema em pastas menores vai ficando cada vez mais confusa para quem precisa encontrar esses testes depois :)

2023-06-12 10:47 UTC, OtavioLins commented on spec/factories/product_categories.rb
> +    name { 'Categoria Teste' }
Aqui fica de sugestão: como esse nome deve ser único, pode ser interessante (e ajudar futuramente nos testes) que vocês usem as sequences do FactoryBot aqui, segue link: https://github.com/thoughtbot/factory_bot/blob/main/GETTING_STARTED.md#sequences

2023-06-12 10:47 UTC, OtavioLins commented on spec/system/categories/admin_register_product_category_spec.rb
> +describe 'Admin registra uma nova categoria' do
Aqui faltou um teste onde ele cria uma categoria com um nome já existente (e também faltou um teste unitário sobre essa validação).

2023-06-12 11:03 UTC, OtavioLins approved these changes

2023-06-12 11:49 UTC, Ricardonovais1 commented on spec/system/categories/admin_register_product_category_spec.rb
> +describe 'Admin registra uma nova categoria' do
Exato, como foi outra dupla que fez o devise e a validação de admin, mas ainda não estava mergeado, estávamos aguardando. Estou listando as pendências para voltar e acertar.

2023-06-12 17:52 UTC, merged