Adicionado homepage a aplicação
TreinaDev/LojaClubeTD10 pull request #13
Opened 2023-06-07 21:05 UTC by MatheusOB21

Esse pull request adiciona:
 - Uma homepage com uma navbar  
 - Um favicon a aplicação
 - Link para página de login
 - Exibir os últimos cinco produtos cadastrados no home page.
 - Menu dropdown de categorias.

![foto_home_page](https://github.com/TreinaDev/LojaClubeTD10/assets/92684440/91112998-4d4a-4c14-8982-395c2dca8b46)

#4 #5

2023-06-07 23:45 UTC, joaorsalmeida requested changes

2023-06-07 23:45 UTC, joaorsalmeida commented on app/views/home/index.html.erb
> +      <img src="..." class="card-img-top" alt="" style="width:200px;height:200px;">
Ao invés dessa imagem 'inválida', vocês podem colocar uma imagem genérica. Tem alguns sites que tem esse serviço ou poderiam colocar uma imagem genérica nos assets da app mesmo.

https://picsum.photos

2023-06-08 11:51 UTC, MatheusOB21 commented on app/views/home/index.html.erb
> +      <img src="..." class="card-img-top" alt="" style="width:200px;height:200px;">
Entendi, iremos fazer essa alteração.

2023-06-08 12:15 UTC, MatheusOB21 commented on app/views/home/index.html.erb
> +      <img src="..." class="card-img-top" alt="" style="width:200px;height:200px;">
Adicionamos um link de imagem válida usando o site citado "picsum" para gerar imagens genéricas, e aproveitamos para alterar a tag img para a tag de image do rails.

2023-06-09 13:59 UTC, joaorsalmeida approved these changes
Senti falta de um teste que mostra o que acontece na tela inicial e não existem produtos. Se puderem adicionar antes do merge seria ótimo ;)

2023-06-09 19:03 UTC, merged