Cadastro de Produto
TreinaDev/LojaClubeTD10 pull request #14
Opened 2023-06-08 04:06 UTC by tbkanzaki

Nessa pull request foram implementadas a tela de cadastro de produto, a tela de detalhe, a listagem e upload de imagem com o ActiveStorage.
Close #10

2023-06-09 14:05 UTC, joaorsalmeida requested changes
Os testes de sistema ficaram bem legais. Mas fiz uns comentários pra ajustarmos em outros pontos.

2023-06-09 14:05 UTC, joaorsalmeida commented on app/controllers/javascript/application.js
Parece que a pasta `javascript` foi toda movida de forma indevida pra dentro de `app/controllers`

2023-06-09 14:05 UTC, joaorsalmeida commented on app/views/products/new.html.erb
> +<div class="text-danger text-center div-max-width"><%= alert %></div>
Esse `alert` e `notice` não deveriam ir para o layout? Na verdade acho que já estão lá.

2023-06-09 14:05 UTC, joaorsalmeida commented on spec/models/product_spec.rb
> +    it 'true (errors.include) quando o código é vazio' do
Estes nomes de teste não estão muito legais. Poderia ser `inválido quando código é vazio`  por exemplo. Ficaria mais legível do que esses `true (errors.include)`

2023-06-09 14:05 UTC, joaorsalmeida commented on app/assets/images/TV.jpg
A pasta `app/assets` serve para arquivos estáticos que vão ser usados na aplicação. Uma logo ou uma imagem fixa que vamos ter no menu ou rodapé por exemplo.

Para o caso deste Pull Request, que as imagens servem para seeds e testes, vocês devem usar a pasta `spec/support` do RSpec. Podem criar uma pasta `imgs` dentro dela pra organizar melhor.

2023-06-09 14:16 UTC, tbkanzaki commented on app/assets/images/TV.jpg
Certo. Ficamos na dúvida se era isso mesmo que deveríamos fazer. Vamos alterar. Obrigada

2023-06-12 10:26 UTC, OtavioLins approved these changes
Gente, estou deixando aprovado pois as mudanças que solicitei são bem pequenas, mas deem uma olhada nos comentários e os resolvam antes de fazer o merge desse PR, ok?

Bom trabalho!

2023-06-12 10:26 UTC, OtavioLins commented on config/locales/errors.pt-BR.yml
> +              invalid: ' deve ser composto por 3 letras e 6 caracteres.'
Aqui um comentário bem pequeno, mas acho que essa mensagem de erro ficou meio confusa. Se eu entendi direito, esse código deve ter 9 caracteres, dos quais 3 são letras e 6 são números, certo? 

Da forma que está escrita, parece que tem tamanho 6 e, desses 6, 3 devem ser letras. Talvez mudar para algo como 'deve ser composto por 3 letras e 6 números', ao invés de 6 caracteres, fique mais claro, já que letras também são caracteres.

2023-06-12 10:26 UTC, OtavioLins commented on spec/models/product_spec.rb
> +    it 'inválido quando o código não é composto por 3 letras e 6 caracteres' do
Aqui fica valendo o comentário anterior, também.

2023-06-12 10:26 UTC, OtavioLins commented on spec/models/product_spec.rb
> +    it 'inválido quando o arquivo anexado não for imagem e no o formato JPEG ou PNG' do
Acho que aqui deveria ser "... não for imagem no formato JPEG ou PNG"

2023-06-12 10:26 UTC, OtavioLins commented on spec/system/products/admin_edit_product_spec.rb
Aqui eu estou entendendo que a parte de login para isso ocorrer não estar feita por conta do MR que faz o cadastro ainda não estar pronto, correto? No caso, é bem importante que vocês lembrem de voltar aqui depois para resolver isso (e adicionar os testes onde usuários não logados/não-administradores tentem acessar essas telas de edição.

2023-06-12 10:26 UTC, OtavioLins commented on spec/system/products/admin_view_products_spec.rb
> +describe 'Usuário acessa index de produtos' do
Aqui eu só queria ter certeza se é para ser um 'Usuário', no geral, ou 'Administrador'. Pergunto pois no nome do arquivo vocês especificam um 'admin' e, aqui, está mais geral como 'Usuário'. Seria bom ajustar um dos dois :)

2023-06-12 10:26 UTC, OtavioLins approved these changes

2023-06-12 12:44 UTC, tbkanzaki commented on spec/system/products/admin_view_products_spec.rb
> +describe 'Usuário acessa index de produtos' do
Ah vdd. Foi falta de atenção mesmo. Vamos corrigir para Administrador.

2023-06-12 12:44 UTC, tbkanzaki commented
Bom dia Otávio.
Obrigada pelos feedbacks. Vamos já já ajustar.
Em relação aos testes separados em pastas menores, creio que todos nós estamos fazendo assim porque no treinamento dos vídeos do warehouse, foi ensinado assim, e acho que também porque não recebemos esse feedback no projeto passado. Eu já ajustei os testes dos produtos. Agora fico na dúvida se pra mandar o commit, ajusto os do testes do Home, que a outra equipe quem fez.

2023-06-12 12:44 UTC, tbkanzaki commented on spec/system/products/admin_edit_product_spec.rb
Isso. Estamos esperando essa parte do login para complementarmos os testes.

2023-06-12 12:44 UTC, tbkanzaki commented on spec/models/product_spec.rb
> +    it 'inválido quando o arquivo anexado não for imagem e no o formato JPEG ou PNG' do
ok.

2023-06-12 12:44 UTC, tbkanzaki commented on config/locales/errors.pt-BR.yml
> +              invalid: ' deve ser composto por 3 letras e 6 caracteres.'
Ah! ok! Na verdade aí seriam 3 letras e 6 números. vamos corrigir a frase.

2023-06-12 12:51 UTC, OtavioLins commented
> Bom dia Otávio. Obrigada pelos feedbacks. Vamos já já ajustar. Em relação aos testes separados em pastas menores, creio que todos nós estamos fazendo assim porque no treinamento dos vídeos do warehouse, foi ensinado assim, e acho que também porque não recebemos esse feedback no projeto passado. Eu já ajustei os testes dos produtos. Agora fico na dúvida se pra mandar o commit, ajusto os do testes do Home, que a outra equipe quem fez.

Sem problemas! Acho que, para ficar melhor para a equipe como um todo (e considerando que hoje tem apresentação), eu sugiro fazer um merge (dos 4 PRs abertos) com os testes da forma que estão organziados e, depois, abrir um PR bem rápido só para isso, sabe? Daí vocês não precisam ficar se preocupando com quem retira o que de que lugar.

Eu comentei em todos os PRs do time sobre isso, só para garantir, daí meio que todo mundo já está ciente, mas qualquer coisa bate um papo em time e daí vocês decidem melhor. Só me avisem depois qual estratégia vocês vão seguir para eu poder ficar ciente na hora de revisar os PRs :)

2023-06-12 13:05 UTC, tbkanzaki commented on spec/system/products/admin_edit_product_spec.rb
Ah, eu fiz um commit há pouco das outras correções. Vamos esperar então. 
Espero que tudo esteja aprovado e mergeado até a hora da apresentação. :-)

2023-06-12 15:11 UTC, tbkanzaki commented on spec/system/products/admin_edit_product_spec.rb
Uma dúvida, como você sugeriu de criarmos os nomes dos arquivos de teste direcionados pra admin e user, então por exemplo, no teste em que o admin cadastra produto e no meu testes tem o describe como 'Administrador cadastra produto', posso colocar aqui nesse mesmo arquivo um teste com it 'como visitante' e outro  com it 'como usuário comum', barrando o acesso nesses dois teste?

E no teste admin_view_product_details_spec.rb, que por enquanto até aqui, o visitante e o usuário comum tem acesso, posso colocar os testes deles nesse mesmo arquivo, ou criamos outro arquivo user_view_product_details_spec.rb?

2023-06-12 16:55 UTC, OtavioLins commented on spec/system/products/admin_edit_product_spec.rb
Os testes onde usuários não-logados e não-admin tentam cadastrar produtos devem ser feitos nesse mesmo arquivo sim! 

Sobre a segunda dúvida: se todos os testes de admin_view_product_details_spec.rb forem só em relação a ver mesmo os detalhes de um produto, então sim, podem estar todos no mesmo arquivo. Daí, eu só sugiro que vocês mudem o nome do arquivo de admin para user, para ficar mais geral.

Se administradores e usuários tiverem ações muito diferentes nessa feature, daí eu sugiro que separem mesmo.

2023-06-12 17:38 UTC, merged