Subcategoria
TreinaDev/LojaClubeTD10 pull request #46
Opened 2023-06-16 22:23 UTC by ClaufSS

Essa PR implementa subcategorias.

É possível criar e editar uma subcategoria através do menu de navegação da aplicação. Também é possível atrelar uma subcategoria a um produto no momento da criação.

Testes unitários garantem o que uma subcategoria não possa ser criada sem um nome e sem uma referência a categoria superior e que o nome não pode ser igual ao de uma categoria ou subcategoria existente.

![image](https://github.com/TreinaDev/LojaClubeTD10/assets/82234131/77c35633-fa29-4ba6-b99f-73b6f2556dee)
![image](https://github.com/TreinaDev/LojaClubeTD10/assets/82234131/3b818c10-6f65-4fcc-8340-8cdb51695933)
![image](https://github.com/TreinaDev/LojaClubeTD10/assets/82234131/b61a9db6-2be7-4dbc-ae33-06498b7a3483)

Close #21
Close #22

2023-06-16 23:20 UTC, ehcelino requested changes
Não encontrei erros no código, não tenho mudanças a sugerir além daquelas que anotei na review. Qualquer dúvida por favor entrar em contato

2023-06-16 23:20 UTC, ehcelino commented on app/views/product_subcategories/edit.html.erb
No lugar de render 'shared/errors', nós estamos usando `<%= render partial: 'form_errors', locals: { object: <OBJ> } %>`, de preferência dentro do formulário (logo abaixo da linha do form_with)

2023-06-16 23:20 UTC, ehcelino commented on app/views/products/_form.html.erb
Não há necessidade do bloco` <% if product.errors.any? %> (...)` se for colocada a partial para tratar os erros.

2023-06-16 23:20 UTC, ehcelino commented on app/views/shared/_errors.html.erb
Esta partial foi excluída em um dos últimos PR's, e em seu lugar deve ser usada a partial _form_errors.html.erb, na pasta application (não há necessidade de escrever o nome da pasta, tudo que está na pasta application é  acessível em qualquer outra view).

2023-06-17 13:52 UTC, felipel7 commented on app/views/shared/_errors.html.erb
Exatamente Eduardo, quando fizemos o pull da branch main, ainda não havia essa partial. Faremos essa pequena alteração durante o merge com a main para resolver os conflitos, uma vez que a pasta "shared" não estará mais presente na main. ;)

2023-06-17 13:56 UTC, felipel7 commented on app/views/products/_form.html.erb
Verdade, esse bloco está relacionado à primeira implementação dos produtos. Vamos padronizar essa parte com o restante da aplicação, utilizando a partial que você recomendou, quando fizermos o merge com a branch main.

2023-06-17 14:00 UTC, felipel7 commented on app/views/product_subcategories/edit.html.erb
Valeu, Eduardo! Vamos fazer dessa maneira que você recomendou. ;)

2023-06-19 12:44 UTC, OtavioLins reviewed
Deixei uns comentários simples, quando vocês me responderem eu possivelmente já aprove.

2023-06-19 12:44 UTC, OtavioLins commented on app/helpers/product_subcategories_helper.rb
Esse helper aqui vocês esqueceram de usar? Ou tá aqui só por acidente?

2023-06-19 14:20 UTC, felipel7 commented on spec/system/admin_register_new_product_spec.rb
> +      Capybara.current_driver = :selenium
Otávio, infelizmente não funcionou dessa forma. Não tenho certeza se isso está relacionado ao Stimulus, mas a única maneira que funcionou foi adicionando o driver do Selenium.

2023-06-19 14:24 UTC, felipel7 commented on app/controllers/product_subcategories_controller.rb
> +  def subcategories
Essa action é utilizada dentro do controller do Stimulus. Lá, realizamos fetch para obter todas as subcategorias de uma categoria específica. A ideia por trás do uso do Stimulus é renderizar dinamicamente as subcategorias quando o usuário seleciona uma categoria no formulário.

2023-06-19 14:29 UTC, felipel7 commented on spec/system/admin_edit_product_subcategoy_spec.rb
Iremos corrigir. :)

2023-06-19 14:29 UTC, felipel7 commented on app/helpers/product_subcategories_helper.rb
Não estamos mais utilizando, iremos remover esse arquivo.

2023-06-19 15:10 UTC, ehcelino approved these changes
Não vi problemas.

2023-06-19 21:38 UTC, merged